#!/usr/bin/env python3
"""
加入客户端 - 使用令牌加入网络
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from urllib.request import urlopen, Request
from urllib.error import URLError


def get_public_key() -> str:
    """获取本机公钥"""
    ssh_dir = Path.home() / ".ssh"
    
    for key_file in ["id_ed25519.pub", "id_rsa.pub"]:
        path = ssh_dir / key_file
        if path.exists():
            return path.read_text().strip()
    
    return ""


def get_local_ip() -> str:
    """获取本机 IP"""
    try:
        result = subprocess.run(
            ["hostname", "-I"],
            capture_output=True,
            text=True
        )
        return result.stdout.strip().split()[0]
    except:
        return "127.0.0.1"


def write_ssh_config(config_text: str, server_id: str) -> bool:
    """写入 SSH config"""
    try:
        ssh_dir = Path.home() / ".ssh"
        ssh_dir.mkdir(mode=0o700, exist_ok=True)
        
        # 使用 config.d 目录
        config_d = ssh_dir / "config.d"
        config_d.mkdir(exist_ok=True)
        
        config_file = config_d / f"topology-{server_id}.conf"
        
        with open(config_file, "w") as f:
            f.write(f"# Auto-generated by topology-manager\n")
            f.write(config_text)
            f.write("\n")
        
        config_file.chmod(0o600)
        print(f"  ✓ SSH config 已写入: {config_file}")
        return True
        
    except Exception as e:
        print(f"  ✗ 写入 SSH config 失败: {e}")
        return False


def join_network(master_url: str, token: str, alias: str = None, write_config: bool = True):
    """加入网络"""
    
    # 收集本机信息
    public_key = get_public_key()
    local_ip = get_local_ip()
    hostname = subprocess.run(["hostname"], capture_output=True, text=True).stdout.strip()
    
    if not alias:
        alias = hostname
    
    print(f"准备加入网络...")
    print(f"  主控地址: {master_url}")
    print(f"  本机别名: {alias}")
    print(f"  本机 IP: {local_ip}")
    print(f"  公钥: {public_key[:50]}..." if public_key else "  公钥: 未找到")
    
    # 构建请求
    data = {
        "alias": alias,
        "ip": local_ip,
        "port": 22,
        "user": Path.home().name,
        "public_key": public_key
    }
    
    # 发送请求
    url = f"{master_url}/api/join/{token}"
    
    try:
        req = Request(
            url,
            data=json.dumps(data).encode(),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        
        with urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode())
        
        print(f"\n✓ 加入成功!")
        print(f"  服务器 ID: {result.get('server_id')}")
        print(f"  公钥已添加: {result.get('key_added', False)}")
        
        # 自动写入 SSH config
        if write_config and "config" in result:
            ssh_config = result["config"].get("ssh_config", "")
            if ssh_config:
                print(f"\n写入 SSH 配置...")
                write_ssh_config(ssh_config, result.get("server_id", alias))
                print(f"\n测试连接:")
                print(f"  ssh {result.get('server_id')} 'hostname'")
        
        return True
        
    except URLError as e:
        print(f"\n✗ 加入失败: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="加入服务器网络")
    parser.add_argument("--master", required=True, help="主控服务器地址")
    parser.add_argument("--token", required=True, help="注册令牌")
    parser.add_argument("--alias", help="本机别名（默认使用 hostname）")
    parser.add_argument("--no-write", action="store_true", help="不写入 SSH config")
    
    args = parser.parse_args()
    
    success = join_network(args.master, args.token, args.alias, write_config=not args.no_write)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()